"""Initial migration with VehicleInfo model

Revision ID: acca66b2608a
Revises: 
Create Date: 2024-12-23 22:58:54.895971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acca66b2608a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_info', schema=None) as batch_op:
        batch_op.drop_index('plate_number')

    op.drop_table('vehicle_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_info',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plate_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('vehicle_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('last_maintenance_date', sa.DATE(), nullable=True),
    sa.Column('next_maintenance_date', sa.DATE(), nullable=True),
    sa.Column('work_type', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vehicle_info', schema=None) as batch_op:
        batch_op.create_index('plate_number', ['plate_number'], unique=True)

    # ### end Alembic commands ###
